/**
 * The single source of every user-visible string (CLAUDE.md §2.2). Nothing the
 * user reads — labels, validation errors, toasts, empty states — is written
 * inline in a component. Later phases fill in their sections here.
 *
 * Voice: formal Modern Standard Arabic, native Riyadh register, active voice,
 * sentence case. Never translated-sounding.
 */

export const ar = {
  site: {
    name: "مستشفى نبض",
    // A short line under the wordmark; used in header/footer.
    tagline: "رعاية صحية موثوقة",
    city: "الرياض",
    addressLine: "طريق الملك عبدالعزيز، حي الملقا، الرياض",
    phone: "+966112000000",
    phoneDisplay: "011 200 0000",
    emergencyPhone: "997",
    email: "info@nabd.example",
    hoursWeekdays: "الأحد – الخميس: 8:00 صباحًا – 8:00 مساءً",
    hoursWeekend: "الجمعة – السبت: العيادات مغلقة",
    hoursEmergency: "قسم الطوارئ يعمل على مدار الساعة",
    foundedYear: 2009,
  },

  nav: {
    home: "الرئيسية",
    about: "عن المستشفى",
    departments: "الأقسام",
    doctors: "الأطباء",
    faq: "الأسئلة الشائعة",
    contact: "تواصل معنا",
    login: "تسجيل الدخول",
    openMenu: "افتح القائمة",
    closeMenu: "أغلق القائمة",
    menuTitle: "التنقّل",
  },

  actions: {
    bookAppointment: "احجز موعدك",
    viewDepartment: "تفاصيل القسم",
    viewDoctor: "الملف الشخصي",
    viewAllDepartments: "كل الأقسام",
    viewAllDoctors: "كل الأطباء",
    viewAllNews: "كل الأخبار",
    backToDepartments: "عودة إلى الأقسام",
    backToDoctors: "عودة إلى الأطباء",
    send: "أرسل الرسالة",
    sending: "جارٍ الإرسال…",
  },

  common: {
    departments: "الأقسام",
    doctors: "الأطباء",
    doctor: "طبيب",
    years: "سنوات",
    year: "سنة",
    yearsExperience: "سنوات الخبرة",
    experience: "الخبرة",
    department: "القسم",
    patients: "مراجع",
    accepting: "يستقبل مراجعين جدد",
    notAccepting: "قائمة الانتظار ممتلئة حاليًا",
    weeklySchedule: "أوقات العمل الأسبوعية",
    day: "اليوم",
    hours: "الفترة",
    to: "–",
    closed: "مغلق",
    // dayOfWeek 0..6 → Sunday..Saturday (matches the Prisma Availability model).
    weekdays: [
      "الأحد",
      "الإثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس",
      "الجمعة",
      "السبت",
    ],
  },

  home: {
    heroTitle: "مستشفى نبض",
    heroLead:
      "رعاية صحية متكاملة تبدأ بنبضة. احجز موعدك مع نخبة من الأطباء في الوقت الذي يناسبك.",
    deptsTitle: "أقسام المستشفى",
    deptsLead: "ستة أقسام تغطي رعايتك من الفحص الأول حتى المتابعة.",
    doctorsTitle: "نخبة من الأطباء",
    doctorsLead: "كوادر استشارية وأخصائية بخبرة طويلة في تشخيص الحالات ومتابعتها.",
    newsTitle: "آخر الأخبار",
    newsLead: "مستجدّات الخدمات والفعاليات في مستشفى نبض.",
  },

  about: {
    title: "عن المستشفى",
    lead: "مستشفى نبض جهة رعاية صحية في الرياض تجمع بين الكفاءة الطبية وتجربة مراجعة واضحة ومنظّمة.",
    historyTitle: "نبذة ومسيرة",
    historyBody: [
      "تأسس مستشفى نبض ليقدّم رعاية صحية موثوقة يسهل الوصول إليها، بعيادات مجهّزة وفريق طبي يضع المريض في مركز كل قرار.",
      "نمت خدماتنا على مدى السنوات لتشمل ستة أقسام رئيسية، مع تطوير مستمر لأنظمة الحجز والمتابعة حتى تصل إلى موعدك في أقل وقت وبأوضح مسار.",
      "نؤمن أن الرعاية الجيدة تبدأ من التنظيم: موعد دقيق، طبيب مختص، ومعلومة واضحة قبل الزيارة وبعدها.",
    ],
    numbersTitle: "أرقام تختصر المسيرة",
    numbersLead: "بيانات محدّثة من قاعدة المستشفى.",
    statDepartments: "قسمًا طبيًا",
    statDoctors: "طبيبًا وطبيبة",
    statYears: "عامًا من الخدمة",
    statEmergency: "طوارئ على مدار الساعة",
    emergencyValue: "24/7",
    missionTitle: "رسالتنا",
    missionBody:
      "أن نقدّم رعاية صحية آمنة وإنسانية، ونجعل الوصول إليها بسيطًا لكل مراجع، بلا تعقيد وبلا انتظار طويل.",
  },

  departments: {
    title: "الأقسام",
    lead: "اختر القسم المناسب لحالتك للاطّلاع على أطبائه وحجز موعدك.",
    empty: "لا توجد أقسام متاحة حاليًا. عاود الزيارة قريبًا.",
  },

  departmentDetail: {
    doctorsTitle: "أطباء القسم",
    doctorsEmpty: "سنعلن عن أطباء هذا القسم قريبًا. تابعنا لمعرفة الجديد.",
    bookCta: "احجز في هذا القسم",
    aboutTitle: "عن القسم",
  },

  doctors: {
    title: "الأطباء",
    lead: "تصفّح الكادر الطبي، أو رشّح النتائج حسب القسم.",
    filterLabel: "رشّح حسب القسم",
    filterAll: "كل الأقسام",
    empty: "لا يوجد أطباء متاحون حاليًا.",
    emptyFiltered: "لا يوجد أطباء في هذا القسم حاليًا. جرّب قسمًا آخر.",
  },

  doctorDetail: {
    bioTitle: "نبذة عن الطبيب",
    scheduleTitle: "أوقات العمل الأسبوعية",
    scheduleLead: "المواعيد بتوقيت الرياض. اختر «احجز مع الطبيب» لعرض الأوقات المتاحة.",
    scheduleEmpty: "لم تُحدَّد أوقات عمل لهذا الطبيب بعد.",
    experienceLabel: "الخبرة",
    departmentLabel: "القسم",
    bookCta: "احجز مع الطبيب",
  },

  faq: {
    title: "الأسئلة الشائعة",
    lead: "إجابات سريعة عن أكثر ما يسأل عنه المراجعون. لم تجد ما تبحث عنه؟ تواصل معنا.",
    empty: "لا توجد أسئلة منشورة حاليًا.",
  },

  contact: {
    title: "تواصل معنا",
    lead: "أرسل استفسارك وسيصلك ردّ فريق المستشفى، أو تفضّل بزيارتنا في أوقات العمل.",
    formTitle: "أرسل رسالة",
    infoTitle: "معلومات التواصل",
    addressLabel: "العنوان",
    phoneLabel: "الهاتف",
    emergencyLabel: "الطوارئ",
    emailLabel: "البريد الإلكتروني",
    hoursLabel: "أوقات العمل",
    fields: {
      fullName: "الاسم الكامل",
      email: "البريد الإلكتروني",
      phone: "رقم الجوال",
      subject: "الموضوع",
      body: "الرسالة",
    },
    placeholders: {
      fullName: "مثال: محمد العتيبي",
      email: "name@example.com",
      phone: "05XXXXXXXX",
      subject: "موضوع الرسالة",
      body: "اكتب تفاصيل استفسارك هنا…",
    },
    successTitle: "وصلت رسالتك",
    successBody: "شكرًا لتواصلك. سيطّلع فريق المستشفى على رسالتك ويعود إليك قريبًا.",
    sendAnother: "أرسل رسالة أخرى",
    errorTitle: "تعذّر إرسال الرسالة",
    errorBody: "حدث خطأ أثناء الإرسال. تحقّق من بياناتك وحاول مرة أخرى.",
    errors: {
      fullNameShort: "أدخل الاسم الكامل (حرفان على الأقل).",
      fullNameLong: "الاسم طويل جدًا.",
      email: "أدخل بريدًا إلكترونيًا صحيحًا.",
      phone: "أدخل رقم جوال سعودي صحيح (يبدأ بـ 05 أو +9665).",
      subjectShort: "أدخل موضوعًا واضحًا (3 أحرف على الأقل).",
      subjectLong: "الموضوع طويل جدًا.",
      bodyShort: "اكتب رسالتك (10 أحرف على الأقل).",
      bodyLong: "الرسالة طويلة جدًا.",
    },
  },

  footer: {
    blurb:
      "مستشفى نبض — رعاية صحية موثوقة في الرياض، بمواعيد تحجزها في دقائق ومتابعة واضحة.",
    quickLinksTitle: "روابط سريعة",
    contactTitle: "تواصل معنا",
    rights: "جميع الحقوق محفوظة لمستشفى نبض.",
  },

  auth: {
    signOut: "تسجيل الخروج",
    login: {
      title: "تسجيل الدخول",
      subtitle: "ادخل إلى حسابك لمتابعة مواعيدك وحجوزاتك.",
      emailLabel: "البريد الإلكتروني",
      passwordLabel: "كلمة المرور",
      submit: "تسجيل الدخول",
      submitting: "جارٍ التحقق…",
      noAccount: "ليس لديك حساب؟",
      registerCta: "أنشئ حسابًا",
    },
    register: {
      title: "إنشاء حساب",
      subtitle: "سجّل بياناتك مرة واحدة لتحجز مواعيدك وتتابعها بسهولة.",
      fields: {
        fullName: "الاسم الكامل",
        email: "البريد الإلكتروني",
        phone: "رقم الجوال",
        nationalId: "رقم الهوية",
        dateOfBirth: "تاريخ الميلاد",
        gender: "الجنس",
        password: "كلمة المرور",
      },
      placeholders: {
        fullName: "مثال: محمد العتيبي",
        email: "name@example.com",
        phone: "05XXXXXXXX",
        nationalId: "١٠ أرقام",
        password: "8 أحرف على الأقل",
      },
      genderMale: "ذكر",
      genderFemale: "أنثى",
      submit: "إنشاء الحساب",
      submitting: "جارٍ الإنشاء…",
      haveAccount: "لديك حساب بالفعل؟",
      loginCta: "سجّل الدخول",
      passwordHint: "استخدم 8 أحرف على الأقل.",
    },
    adminLogin: {
      title: "دخول الإدارة",
      subtitle: "بوابة موظفي مستشفى نبض. الدخول مخصّص للحسابات الإدارية.",
      emailLabel: "البريد الإلكتروني",
      passwordLabel: "كلمة المرور",
      submit: "دخول لوحة التحكم",
      submitting: "جارٍ التحقق…",
    },
    errors: {
      fullNameShort: "أدخل الاسم الكامل (حرفان على الأقل).",
      fullNameLong: "الاسم طويل جدًا.",
      email: "أدخل بريدًا إلكترونيًا صحيحًا.",
      phone: "أدخل رقم جوال سعودي صحيح (يبدأ بـ 05 أو +9665).",
      nationalId: "رقم الهوية يجب أن يتكوّن من 10 أرقام.",
      password: "كلمة المرور يجب ألا تقل عن 8 أحرف.",
      dateOfBirth: "أدخل تاريخ ميلاد صحيح.",
      dateOfBirthFuture: "تاريخ الميلاد يجب أن يكون في الماضي.",
      gender: "اختر الجنس.",
      credentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
      rateLimited: "محاولات كثيرة. انتظر دقيقة ثم أعد المحاولة.",
      emailTaken: "هذا البريد الإلكتروني مسجّل بالفعل. سجّل الدخول بدلًا من ذلك.",
      generic: "تعذّر إتمام الطلب. حاول مرة أخرى.",
    },
    // Minimal authenticated placeholders; the full screens arrive in later phases.
    patientHome: {
      title: "مواعيدي",
      placeholder: "ستظهر هنا مواعيدك القادمة والسابقة بعد بناء نظام الحجز.",
    },
    adminHome: {
      title: "لوحة التحكم",
      welcome: (name: string) => `مرحبًا، ${name}.`,
      placeholder: "لوحة المؤشرات والإدارة قيد الإنشاء في المرحلة القادمة.",
    },
  },

  // Appointment status labels (CLAUDE.md §4).
  statuses: {
    PENDING: "بانتظار التأكيد",
    CONFIRMED: "مؤكد",
    COMPLETED: "مكتمل",
    CANCELLED: "ملغي",
    NO_SHOW: "لم يحضر",
  },

  booking: {
    title: "احجز موعدك",
    lead: "ثلاث خطوات: اختر القسم، ثم الطبيب، ثم اليوم والوقت المناسب.",
    steps: {
      department: "القسم",
      doctor: "الطبيب",
      datetime: "الموعد",
    },
    chooseDepartment: "اختر القسم",
    chooseDoctor: "اختر الطبيب",
    chooseDate: "اختر اليوم",
    chooseSlot: "اختر الوقت",
    slotsLead: "الأوقات بتوقيت الرياض. الأوقات المحجوزة تظهر معطّلة.",
    noSlots: "لا تتوفر مواعيد في هذا اليوم. جرّب يومًا آخر.",
    weekendNote: "العيادات تعمل من الأحد إلى الخميس.",
    reasonLabel: "سبب الزيارة (اختياري)",
    reasonPlaceholder: "مثال: متابعة دورية",
    reviewTitle: "راجع الموعد",
    confirmCta: "أكّد الحجز",
    confirming: "جارٍ تأكيد الحجز…",
    loginPrompt: "سجّل الدخول لإتمام الحجز.",
    loginCta: "تسجيل الدخول للمتابعة",
    changeDoctor: "تغيير الطبيب",
    changeDepartment: "تغيير القسم",
    slotReasons: {
      cutoff: "انتهى وقت الحجز",
      booked: "محجوز",
      timeoff: "غير متاح",
    },
    successTitle: "تم حجز موعدك",
    successLead: "احتفظ برقم ملفك. حالة الموعد الآن «بانتظار التأكيد».",
    slip: {
      title: "بيانات الموعد",
      fileNumber: "رقم الملف",
      doctor: "الطبيب",
      department: "القسم",
      date: "التاريخ",
      time: "الوقت",
      status: "الحالة",
      print: "طباعة",
      toAppointments: "الذهاب إلى مواعيدي",
    },
    errors: {
      slotUnavailable: "لم يعد هذا الوقت متاحًا. اختر وقتًا آخر.",
      slotTaken: "حُجز هذا الوقت للتو. اختر وقتًا آخر.",
      invalid: "تعذّر إتمام الحجز. تحقّق من اختيارك وحاول مجددًا.",
      auth: "سجّل الدخول لإتمام الحجز.",
    },
  },

  appointments: {
    title: "مواعيدي",
    lead: "تابع مواعيدك القادمة والسابقة وحالتها.",
    upcoming: "القادمة",
    past: "السابقة",
    emptyUpcoming: "لا توجد مواعيد قادمة. احجز موعدك الآن.",
    emptyPast: "لا توجد مواعيد سابقة.",
    bookCta: "احجز موعدًا",
    labels: {
      doctor: "الطبيب",
      department: "القسم",
      date: "التاريخ",
      time: "الوقت",
      fileNumber: "رقم الملف",
      reason: "سبب الزيارة",
    },
    cancelCta: "إلغاء الموعد",
    cancelling: "جارٍ الإلغاء…",
    cancelTitle: "إلغاء الموعد",
    cancelBody: "هل تريد إلغاء هذا الموعد؟ لا يمكن التراجع بعد الإلغاء.",
    cancelConfirm: "نعم، ألغِ الموعد",
    cancelKeep: "الاحتفاظ بالموعد",
    cancelSuccess: "تم إلغاء الموعد.",
    cancelError: "تعذّر إلغاء الموعد. حاول مرة أخرى.",
    cannotCancel: "لا يمكن إلغاء هذا الموعد.",
  },

  admin: {
    nav: {
      overview: "نظرة عامة",
      appointments: "المواعيد",
      patients: "المرضى",
      doctors: "الأطباء",
      departments: "الأقسام",
      news: "الأخبار",
      messages: "الرسائل",
      signOut: "تسجيل الخروج",
      menuTitle: "لوحة التحكم",
    },
    common: {
      search: "بحث",
      filter: "تصفية",
      all: "الكل",
      apply: "تطبيق",
      reset: "إعادة تعيين",
      actions: "إجراءات",
      save: "حفظ",
      saving: "جارٍ الحفظ…",
      cancel: "إلغاء",
      create: "إضافة",
      edit: "تعديل",
      delete: "حذف",
      confirm: "تأكيد",
      close: "إغلاق",
      loading: "جارٍ التحميل…",
      noResults: "لا توجد نتائج مطابقة.",
      prev: "السابق",
      next: "التالي",
      page: "صفحة",
      of: "من",
      status: "الحالة",
      department: "القسم",
      doctor: "الطبيب",
      date: "التاريخ",
      time: "الوقت",
      genericError: "حدث خطأ. حاول مرة أخرى.",
    },
    overview: {
      title: "نظرة عامة",
      kpiToday: "مواعيد اليوم",
      kpiWeek: "مواعيد هذا الأسبوع",
      kpiActivePatients: "المرضى النشطون",
      kpiCancelRate: "نسبة الإلغاء",
      chartPerDayTitle: "المواعيد خلال آخر 30 يومًا",
      chartPerDeptTitle: "المواعيد حسب القسم",
      recentTitle: "أحدث النشاط",
      recentEmpty: "لا يوجد نشاط بعد.",
      chartAppointments: "المواعيد",
    },
    appointments: {
      title: "المواعيد",
      searchPlaceholder: "ابحث باسم المريض أو رقم الملف",
      colPatient: "المريض",
      colFileNumber: "رقم الملف",
      colDoctor: "الطبيب",
      colDepartment: "القسم",
      colDateTime: "الموعد",
      colStatus: "الحالة",
      confirm: "تأكيد",
      complete: "إكمال",
      noShow: "لم يحضر",
      cancel: "إلغاء",
      empty: "لا توجد مواعيد مطابقة للتصفية.",
      updated: "تم تحديث حالة الموعد.",
    },
    patients: {
      title: "المرضى",
      searchPlaceholder: "ابحث بالاسم أو رقم الملف",
      colName: "الاسم",
      colFileNumber: "رقم الملف",
      colPhone: "الجوال",
      colAppointments: "المواعيد",
      view: "عرض السجل",
      detailTitle: "سجل المريض",
      historyTitle: "المواعيد",
      noHistory: "لا توجد مواعيد لهذا المريض.",
      empty: "لا يوجد مرضى مطابقون.",
      gender: "الجنس",
      dateOfBirth: "تاريخ الميلاد",
    },
    doctors: {
      title: "الأطباء",
      colName: "الاسم",
      colDepartment: "القسم",
      colExperience: "الخبرة",
      colAccepting: "الاستقبال",
      accepting: "يستقبل",
      notAccepting: "متوقف",
      toggleAccepting: "تبديل الاستقبال",
      delete: "حذف الطبيب",
      deleteBlocked: "لا يمكن حذف طبيب لديه مواعيد قادمة. ألغِ مواعيده أولًا.",
      deleted: "تم حذف الطبيب.",
      empty: "لا يوجد أطباء.",
    },
    departments: {
      title: "الأقسام",
      colName: "القسم",
      colDoctors: "الأطباء",
      colOrder: "الترتيب",
      colActive: "الحالة",
      active: "مُفعّل",
      inactive: "متوقف",
      activate: "تفعيل",
      deactivate: "إيقاف",
      moveUp: "أعلى",
      moveDown: "أسفل",
      updated: "تم تحديث القسم.",
      empty: "لا توجد أقسام.",
    },
    news: {
      title: "الأخبار",
      colTitle: "العنوان",
      colStatus: "الحالة",
      colDate: "تاريخ النشر",
      published: "منشور",
      draft: "مسودة",
      publish: "نشر",
      unpublish: "إلغاء النشر",
      delete: "حذف",
      deleted: "تم حذف الخبر.",
      updated: "تم تحديث الخبر.",
      empty: "لا توجد أخبار.",
      draftDate: "—",
    },
    messages: {
      title: "الرسائل",
      unreadBadge: "غير مقروءة",
      from: "من",
      markRead: "تعليم كمقروء",
      read: "مقروءة",
      unread: "جديدة",
      empty: "لا توجد رسائل.",
      marked: "تم تعليم الرسالة كمقروءة.",
    },
  },

  metadata: {
    home: {
      title: "مستشفى نبض",
      description:
        "مستشفى نبض — رعاية صحية موثوقة ومواعيد تحجزها في دقائق مع نخبة من الأطباء.",
    },
    book: {
      title: "احجز موعدك",
      description: "احجز موعدك في مستشفى نبض: اختر القسم والطبيب والوقت المناسب.",
    },
    login: {
      title: "تسجيل الدخول",
      description: "سجّل الدخول إلى حسابك في مستشفى نبض لإدارة مواعيدك.",
    },
    register: {
      title: "إنشاء حساب",
      description: "أنشئ حسابًا في مستشفى نبض لحجز المواعيد ومتابعتها.",
    },
    adminLogin: {
      title: "دخول الإدارة",
      description: "بوابة دخول موظفي وإدارة مستشفى نبض.",
    },
    dashboard: {
      title: "لوحة التحكم",
      description: "لوحة تحكم إدارة مستشفى نبض.",
    },
    myAppointments: {
      title: "مواعيدي",
      description: "مواعيدك القادمة والسابقة في مستشفى نبض.",
    },
    about: {
      title: "عن المستشفى",
      description:
        "تعرّف على مستشفى نبض: مسيرته وأقسامه وكادره الطبي ورسالته في تقديم رعاية صحية موثوقة في الرياض.",
    },
    departments: {
      title: "الأقسام",
      description:
        "استعرض أقسام مستشفى نبض الطبية واختر القسم المناسب لحالتك لحجز موعدك.",
    },
    doctors: {
      title: "الأطباء",
      description:
        "الكادر الطبي في مستشفى نبض من استشاريين وأخصائيين. رشّح الأطباء حسب القسم واحجز موعدك.",
    },
    faq: {
      title: "الأسئلة الشائعة",
      description:
        "إجابات عن أكثر أسئلة المراجعين شيوعًا حول المواعيد والخدمات والحسابات في مستشفى نبض.",
    },
    contact: {
      title: "تواصل معنا",
      description:
        "معلومات التواصل مع مستشفى نبض: العنوان والهاتف وأوقات العمل، ونموذج لإرسال استفسارك.",
    },
  },

  /**
   * Composed strings that interpolate data. Kept here so no Arabic text is
   * written inline in a component (CLAUDE.md §2.2), while still allowing values
   * to be woven in.
   */
  build: {
    doctorsInDepartment: (deptName: string) => `أطباء قسم ${deptName}`,
    bookInDepartment: (deptName: string) => `احجز في قسم ${deptName}`,
    bookWithDoctor: (doctorName: string) => `احجز مع ${doctorName}`,
    doctorMetaDescription: (
      doctorName: string,
      title: string,
      deptName: string,
    ) => `${doctorName}، ${title} في قسم ${deptName} بمستشفى نبض. اطّلع على نبذة الطبيب وأوقات عمله واحجز موعدك.`,
    departmentMetaDescription: (deptName: string) =>
      `قسم ${deptName} في مستشفى نبض: نبذة عن القسم وأطبّاؤه وحجز المواعيد.`,
    countInDepartment: (count: number) =>
      count === 1 ? `طبيب واحد` : `${count} أطباء`,
  },
} as const;

export type Content = typeof ar;

export default ar;
