/**
 * The single source of every user-visible string (CLAUDE.md §2.2). Nothing the
 * user reads — labels, validation errors, toasts, empty states — is written
 * inline in a component. Each phase fills in its section here.
 *
 * Voice: formal Modern Standard Arabic, native Riyadh register, active voice,
 * sentence case. Never translated-sounding.
 */

export const ar = {
  site: {
    name: "مستشفى نبض",
    tagline: "رعاية صحية موثوقة",
    city: "الرياض",
  },

  actions: {
    bookAppointment: "احجز موعدك",
    signOut: "تسجيل الخروج",
    signIn: "تسجيل الدخول",
  },

  nav: {
    home: "الرئيسية",
    departments: "الأقسام",
    doctors: "الأطباء",
    about: "عن المستشفى",
    news: "الأخبار",
    faq: "الأسئلة الشائعة",
    contact: "تواصل معنا",
    book: "احجز موعدك",
    login: "تسجيل الدخول",
    myAppointments: "مواعيدي",
    dashboard: "لوحة التحكم",
    openMenu: "افتح القائمة",
    closeMenu: "أغلق القائمة",
    primary: "التنقل الرئيسي",
  },

  footer: {
    blurb:
      "مستشفى نبض في الرياض — رعاية صحية متكاملة يقدّمها فريق من الأطباء عبر ستة أقسام، مع حجز إلكتروني للمواعيد.",
    exploreTitle: "تصفّح",
    contactTitle: "تواصل",
    hoursTitle: "أوقات العمل",
    address: "طريق الملك فهد، حي العليا، الرياض",
    phone: "0112000000",
    email: "info@nabd.example",
    hoursClinics: "العيادات: الأحد – الخميس، 8 صباحًا – 8 مساءً",
    hoursEmergency: "الطوارئ: 24 ساعة طوال أيام الأسبوع",
    rights: "جميع الحقوق محفوظة لمستشفى نبض.",
    disclaimer: "مشروع تخرّج لأغراض تعليمية. المحتوى والبيانات كلها تجريبية.",
  },

  common: {
    all: "الكل",
    viewAll: "عرض الكل",
    readMore: "اقرأ المزيد",
    backHome: "العودة إلى الرئيسية",
    back: "رجوع",
    loading: "جارٍ التحميل…",
    yearsExperienceSuffix: "سنة خبرة",
    doctorsCountSuffix: "طبيب",
  },

  status: {
    PENDING: "بانتظار التأكيد",
    CONFIRMED: "مؤكد",
    COMPLETED: "مكتمل",
    CANCELLED: "ملغي",
    NO_SHOW: "لم يحضر",
  },

  home: {
    heroTitle: "مستشفى نبض",
    heroLead:
      "رعاية صحية متكاملة تبدأ بنبضة. احجز موعدك مع نخبة من الأطباء في الوقت الذي يناسبك.",
    departmentsTitle: "الأقسام",
    departmentsLead: "ستة أقسام تغطّي احتياجات الأسرة، من الباطنية إلى الطوارئ.",
    doctorsTitle: "أطباء مختارون",
    doctorsLead: "نخبة من الاستشاريين والأخصائيين في خدمتك.",
    newsTitle: "آخر الأخبار",
    newsLead: "مستجدّات المستشفى وخدماته الجديدة.",
    ctaTitle: "احجز موعدك اليوم",
    ctaLead: "اختر القسم والطبيب والوقت المناسب في خطوات معدودة.",
  },

  about: {
    title: "عن مستشفى نبض",
    lead: "مستشفى يضع المريض في قلب الرعاية، بخدمات تشخيصية وعلاجية متكاملة في الرياض.",
    historyTitle: "نبذة",
    history:
      "تأسّس مستشفى نبض ليقدّم رعاية صحية موثوقة تجمع بين الكفاءة الطبية وحسن التعامل. نعمل عبر ستة أقسام رئيسية بفريق من الاستشاريين والأخصائيين، ونحرص على أن تكون تجربة المراجع سهلة من لحظة الحجز حتى انتهاء الموعد. يعمل قسم الطوارئ على مدار الساعة، فيما تستقبل العيادات مراجعيها من الأحد إلى الخميس.",
    missionTitle: "رسالتنا",
    mission:
      "تقديم رعاية صحية آمنة وفي متناول الجميع، تحترم وقت المريض وخصوصيته، وتستند إلى أحدث الممارسات الطبية.",
    statsTitle: "بالأرقام",
    statDepartments: "أقسام طبية",
    statDoctors: "طبيب وطبيبة",
    statYears: "عامًا من الخبرة المجمّعة",
  },

  departments: {
    title: "الأقسام",
    lead: "اختر القسم المناسب لحالتك للاطّلاع على أطبائه وحجز موعدك.",
    doctorsHere: "أطباء القسم",
    bookHere: "احجز في هذا القسم",
    backToDepartments: "كل الأقسام",
    noDoctors: "لا يوجد أطباء مسجّلون في هذا القسم حاليًا.",
    notFound: "القسم غير موجود",
  },

  doctors: {
    title: "الأطباء",
    lead: "تصفّح أطباء المستشفى واحجز مع من يناسبك.",
    filterLabel: "تصفية حسب القسم",
    accepting: "يستقبل مرضى جدد",
    notAccepting: "لا يستقبل حاليًا",
    availabilityTitle: "أوقات العمل الأسبوعية",
    availabilityNone: "لم تُحدَّد أوقات عمل بعد.",
    bookWith: "احجز مع الطبيب",
    inDepartment: "القسم",
    experience: "الخبرة",
    notFound: "الطبيب غير موجود",
    day: "اليوم",
    from: "من",
    to: "إلى",
  },

  faq: {
    title: "الأسئلة الشائعة",
    lead: "إجابات سريعة عن أكثر ما يسأل عنه المراجعون.",
    empty: "لا توجد أسئلة منشورة بعد.",
  },

  contact: {
    title: "تواصل معنا",
    lead: "أرسل استفسارك وسنعود إليك في أقرب وقت.",
    infoTitle: "معلومات التواصل",
    addressLabel: "العنوان",
    phoneLabel: "الهاتف",
    emailLabel: "البريد الإلكتروني",
    hoursLabel: "أوقات العمل",
    formTitle: "أرسل رسالة",
    fields: {
      fullName: "الاسم الكامل",
      email: "البريد الإلكتروني",
      phone: "رقم الجوال",
      subject: "الموضوع",
      body: "نص الرسالة",
      bodyPlaceholder: "اكتب استفسارك هنا…",
    },
    submit: "إرسال الرسالة",
    submitting: "جارٍ الإرسال…",
    success: "تم إرسال رسالتك. سنتواصل معك قريبًا.",
    error: "تعذّر إرسال الرسالة. أعد المحاولة.",
    validation: {
      fullNameRequired: "أدخل الاسم الكامل.",
      emailInvalid: "أدخل بريدًا إلكترونيًا صحيحًا.",
      phoneInvalid: "أدخل رقم جوال سعودي صحيح مثل 05XXXXXXXX.",
      subjectRequired: "أدخل موضوع الرسالة.",
      bodyRequired: "اكتب نص الرسالة.",
      bodyTooShort: "الرسالة قصيرة جدًا؛ أضف مزيدًا من التفاصيل.",
    },
  },

  booking: {
    title: "حجز موعد",
    lead: "اختر القسم ثم الطبيب ثم الوقت المناسب.",
    stepLabel: "الخطوة",
    ofLabel: "من",
    steps: {
      department: "القسم",
      doctor: "الطبيب",
      datetime: "الموعد",
    },
    chooseDepartment: "اختر القسم",
    chooseDoctor: "اختر الطبيب",
    chooseDate: "اختر التاريخ",
    chooseSlot: "اختر الوقت",
    weekdaysHint: "المواعيد متاحة من الأحد إلى الخميس.",
    noDoctors: "لا يوجد أطباء متاحون في هذا القسم.",
    noSlots: "لا توجد مواعيد متاحة في هذا اليوم. جرّب يومًا آخر.",
    notAccepting: "هذا الطبيب لا يستقبل مرضى جدد حاليًا.",
    slotReason: {
      past: "انتهى",
      too_soon: "قريب جدًا",
      timeoff: "غير متاح",
      booked: "محجوز",
    },
    reasonLabel: "سبب الزيارة (اختياري)",
    reasonPlaceholder: "مثال: متابعة دورية",
    next: "التالي",
    back: "السابق",
    change: "تغيير",
    confirm: "تأكيد الحجز",
    confirming: "جارٍ الحجز…",
    loginRequired: "سجّل الدخول لإتمام حجز موعدك.",
    loginCta: "تسجيل الدخول ومتابعة الحجز",
    success: "تم حجز الموعد.",
    conflict: "هذا الموعد لم يعد متاحًا. اختر وقتًا آخر.",
    invalidSlot: "الوقت المختار غير صالح. اختر وقتًا من الأوقات المتاحة.",
    genericError: "تعذّر إتمام الحجز. أعد المحاولة.",
    summaryTitle: "مراجعة الحجز",
    slip: {
      title: "تفاصيل الموعد",
      fileNumber: "رقم الملف",
      doctor: "الطبيب",
      department: "القسم",
      date: "التاريخ",
      time: "الوقت",
      status: "الحالة",
      reason: "سبب الزيارة",
      print: "طباعة",
      done: "تم الحجز بنجاح",
      viewAppointments: "عرض مواعيدي",
    },
  },

  appointments: {
    title: "مواعيدي",
    lead: "تابع مواعيدك القادمة والسابقة وألغِ ما تحتاج.",
    upcoming: "المواعيد القادمة",
    past: "المواعيد السابقة",
    empty: "لا توجد لديك مواعيد قادمة.",
    emptyLead: "احجز موعدك الأول مع الطبيب المناسب.",
    emptyPast: "لا توجد مواعيد سابقة.",
    bookCta: "احجز موعدًا",
    columns: {
      date: "التاريخ",
      time: "الوقت",
      doctor: "الطبيب",
      department: "القسم",
      status: "الحالة",
      reason: "سبب الزيارة",
    },
    fileNumberLabel: "رقم الملف",
    cancel: "إلغاء الموعد",
    cancelConfirmTitle: "إلغاء الموعد؟",
    cancelConfirmBody: "سيتم إلغاء هذا الموعد ولا يمكن التراجع. يمكنك الحجز من جديد في وقت آخر.",
    cancelConfirmAction: "نعم، ألغِ الموعد",
    keep: "تراجع",
    cancelSuccess: "تم إلغاء الموعد.",
    cancelError: "تعذّر إلغاء الموعد. أعد المحاولة.",
    cancelTooLate: "لا يمكن إلغاء الموعد قبل أقل من ٤ ساعات من وقته.",
    cancelNotAllowed: "لا يمكن إلغاء هذا الموعد.",
  },

  dash: {
    brand: "لوحة تحكم نبض",
    backToSite: "الموقع العام",
    nav: {
      overview: "نظرة عامة",
      appointments: "المواعيد",
      patients: "المرضى",
      doctors: "الأطباء",
      departments: "الأقسام",
      news: "الأخبار",
      messages: "الرسائل",
    },
    common: {
      save: "حفظ",
      saving: "جارٍ الحفظ…",
      cancel: "إلغاء",
      create: "إضافة",
      add: "إضافة",
      edit: "تعديل",
      delete: "حذف",
      deleting: "جارٍ الحذف…",
      actions: "إجراءات",
      confirmDeleteTitle: "تأكيد الحذف",
      confirmDeleteBody: "لا يمكن التراجع عن هذا الإجراء.",
      confirmDelete: "نعم، احذف",
      keep: "تراجع",
      saved: "تم الحفظ.",
      saveError: "تعذّر الحفظ. تحقّق من الحقول وأعد المحاولة.",
      deleted: "تم الحذف.",
      deleteError: "تعذّر الحذف.",
      slugTaken: "المعرّف مستخدم مسبقًا.",
      yes: "نعم",
      no: "لا",
      none: "—",
      search: "بحث",
      clearFilters: "مسح التصفية",
      all: "الكل",
      loading: "جارٍ التحميل…",
    },
    overview: {
      title: "نظرة عامة",
      lead: "ملخّص نشاط المستشفى اليوم وهذا الأسبوع.",
      kpiToday: "مواعيد اليوم",
      kpiWeek: "مواعيد هذا الأسبوع",
      kpiActivePatients: "المرضى النشطون",
      kpiCancellation: "نسبة الإلغاء",
      chartPerDay: "المواعيد خلال آخر ٣٠ يومًا",
      chartPerDept: "المواعيد حسب القسم",
      recent: "أحدث الحجوزات",
      noRecent: "لا توجد حجوزات حديثة.",
    },
    appointments: {
      title: "المواعيد",
      lead: "راجع المواعيد وحدّث حالاتها.",
      searchPlaceholder: "ابحث بالاسم أو رقم الملف",
      filterStatus: "الحالة",
      filterDepartment: "القسم",
      filterDoctor: "الطبيب",
      walkIn: "حجز مباشر",
      empty: "لا توجد مواعيد مطابقة.",
      updated: "تم تحديث حالة الموعد.",
      updateError: "تعذّر تحديث الحالة.",
      confirm: "تأكيد",
      complete: "إكمال",
      noShow: "لم يحضر",
      cancel: "إلغاء",
      columns: {
        datetime: "الموعد",
        patient: "المريض",
        fileNumber: "رقم الملف",
        doctor: "الطبيب",
        department: "القسم",
        status: "الحالة",
      },
    },
    walkIn: {
      title: "حجز مباشر",
      lead: "احجز موعدًا نيابةً عن مريض.",
      patient: "المريض",
      selectPatient: "اختر المريض",
      department: "القسم",
      doctor: "الطبيب",
      date: "التاريخ",
      slot: "الوقت",
      reason: "سبب الزيارة (اختياري)",
      submit: "تأكيد الحجز",
      submitting: "جارٍ الحجز…",
      success: "تم إنشاء الموعد.",
      conflict: "هذا الوقت لم يعد متاحًا.",
      error: "تعذّر إنشاء الموعد.",
      noSlots: "لا توجد أوقات متاحة في هذا اليوم.",
    },
    patients: {
      title: "المرضى",
      lead: "سجلّ المرضى وتاريخ مواعيدهم.",
      searchPlaceholder: "ابحث بالاسم أو رقم الملف",
      empty: "لا يوجد مرضى مطابقون.",
      historyTitle: "تاريخ المواعيد",
      noHistory: "لا توجد مواعيد لهذا المريض.",
      close: "إغلاق",
      columns: {
        fileNumber: "رقم الملف",
        name: "الاسم",
        phone: "الجوال",
        gender: "الجنس",
        appointments: "المواعيد",
        registered: "تاريخ التسجيل",
      },
    },
    doctors: {
      title: "الأطباء",
      lead: "أضف الأطباء وعدّل بياناتهم وأوقات عملهم.",
      add: "إضافة طبيب",
      edit: "تعديل الطبيب",
      empty: "لا يوجد أطباء.",
      deleteBlocked: "لا يمكن حذف طبيب مرتبط بمواعيد.",
      availability: "أوقات العمل",
      editAvailability: "تعديل أوقات العمل",
      availabilitySaved: "تم حفظ أوقات العمل.",
      addRow: "إضافة فترة",
      removeRow: "حذف",
      columns: {
        name: "الاسم",
        title: "اللقب",
        department: "القسم",
        experience: "الخبرة",
        accepting: "يستقبل",
      },
      fields: {
        slug: "المعرّف (بالإنجليزية)",
        fullNameAr: "الاسم الكامل",
        title: "اللقب",
        department: "القسم",
        bio: "نبذة",
        yearsExperience: "سنوات الخبرة",
        isAcceptingPatients: "يستقبل مرضى جدد",
        dayOfWeek: "اليوم",
        startTime: "من",
        endTime: "إلى",
        slotMinutes: "مدة الموعد (دقيقة)",
      },
    },
    departments: {
      title: "الأقسام",
      lead: "أضف الأقسام ورتّبها وفعّلها.",
      add: "إضافة قسم",
      edit: "تعديل القسم",
      empty: "لا توجد أقسام.",
      active: "مُفعّل",
      inactive: "معطّل",
      activate: "تفعيل",
      deactivate: "تعطيل",
      moveUp: "أعلى",
      moveDown: "أسفل",
      deleteBlocked: "لا يمكن حذف قسم مرتبط بأطباء أو مواعيد.",
      columns: {
        name: "القسم",
        doctors: "الأطباء",
        order: "الترتيب",
        status: "الحالة",
      },
      fields: {
        slug: "المعرّف (بالإنجليزية)",
        nameAr: "اسم القسم",
        descriptionAr: "الوصف",
        icon: "الأيقونة",
        isActive: "مُفعّل",
      },
    },
    news: {
      title: "الأخبار",
      lead: "أضف الأخبار وانشرها أو احفظها كمسودة.",
      add: "إضافة خبر",
      edit: "تعديل الخبر",
      empty: "لا توجد أخبار.",
      draft: "مسودة",
      published: "منشور",
      columns: {
        title: "العنوان",
        status: "الحالة",
        publishedAt: "تاريخ النشر",
      },
      fields: {
        slug: "المعرّف (بالإنجليزية)",
        titleAr: "العنوان",
        excerptAr: "المقتطف",
        bodyAr: "النص",
        published: "منشور",
      },
    },
    messages: {
      title: "الرسائل",
      lead: "رسائل التواصل الواردة.",
      empty: "لا توجد رسائل.",
      markRead: "تعليم كمقروء",
      markUnread: "تعليم كغير مقروء",
      unread: "غير مقروء",
      read: "مقروء",
      detailTitle: "تفاصيل الرسالة",
      close: "إغلاق",
      columns: {
        from: "المرسِل",
        subject: "الموضوع",
        date: "التاريخ",
        status: "الحالة",
      },
    },
  },

  auth: {
    fields: {
      email: "البريد الإلكتروني",
      emailPlaceholder: "name@example.com",
      password: "كلمة المرور",
      passwordPlaceholder: "٨ أحرف على الأقل",
      fullName: "الاسم الكامل",
      fullNamePlaceholder: "الاسم الأول واسم العائلة",
      phone: "رقم الجوال",
      phonePlaceholder: "05XXXXXXXX",
      nationalId: "رقم الهوية الوطنية",
      nationalIdPlaceholder: "١٠ أرقام",
      dateOfBirth: "تاريخ الميلاد",
      gender: "الجنس",
    },

    gender: {
      male: "ذكر",
      female: "أنثى",
    },

    login: {
      title: "تسجيل الدخول",
      lead: "أدخل بياناتك للوصول إلى مواعيدك.",
      submit: "تسجيل الدخول",
      submitting: "جارٍ تسجيل الدخول…",
      noAccount: "ليس لديك حساب؟",
      registerLink: "أنشئ حسابًا جديدًا",
      invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
      rateLimited: "تجاوزت عدد المحاولات المسموح بها. أعد المحاولة بعد قليل.",
      genericError: "تعذّر تسجيل الدخول. أعد المحاولة.",
    },

    register: {
      title: "إنشاء حساب",
      lead: "سجّل بياناتك لحجز مواعيدك ومتابعتها.",
      submit: "إنشاء الحساب",
      submitting: "جارٍ إنشاء الحساب…",
      haveAccount: "لديك حساب بالفعل؟",
      loginLink: "سجّل الدخول",
      success: "تم إنشاء حسابك. سجّل الدخول للمتابعة.",
      emailTaken: "هذا البريد الإلكتروني مسجّل مسبقًا.",
      nationalIdTaken: "رقم الهوية مسجّل مسبقًا.",
      genericError: "تعذّر إنشاء الحساب. أعد المحاولة.",
    },

    adminLogin: {
      title: "دخول الإدارة",
      lead: "هذه البوابة مخصّصة لموظفي المستشفى.",
      submit: "دخول لوحة التحكم",
    },

    validation: {
      emailRequired: "أدخل البريد الإلكتروني.",
      emailInvalid: "أدخل بريدًا إلكترونيًا صحيحًا.",
      passwordRequired: "أدخل كلمة المرور.",
      passwordTooShort: "يجب ألا تقل كلمة المرور عن ٨ أحرف.",
      fullNameRequired: "أدخل الاسم الكامل.",
      fullNameTooShort: "أدخل الاسم الأول واسم العائلة على الأقل.",
      phoneRequired: "أدخل رقم الجوال.",
      phoneInvalid: "أدخل رقم جوال سعودي صحيح مثل 05XXXXXXXX.",
      nationalIdRequired: "أدخل رقم الهوية.",
      nationalIdInvalid: "يجب أن يتكوّن رقم الهوية من ١٠ أرقام.",
      dateOfBirthRequired: "أدخل تاريخ الميلاد.",
      dateOfBirthInvalid: "أدخل تاريخ ميلاد صحيح.",
      dateOfBirthFuture: "لا يمكن أن يكون تاريخ الميلاد في المستقبل.",
      genderRequired: "اختر الجنس.",
    },
  },

  // Minimal authenticated landing surfaces. Phase 4 (my-appointments) and
  // Phase 5 (dashboard) replace these placeholders with the real screens.
  dashboard: {
    placeholderTitle: "لوحة التحكم",
    placeholderLead: "مرحبًا بك في لوحة تحكم مستشفى نبض.",
  },
  myAppointments: {
    placeholderTitle: "مواعيدي",
    placeholderLead: "ستظهر هنا مواعيدك القادمة والسابقة.",
  },

  errors: {
    badRequest: "البيانات المُرسلة غير صحيحة.",
    unauthorized: "يلزم تسجيل الدخول للمتابعة.",
    forbidden: "لا تملك صلاحية الوصول إلى هذه الصفحة.",
    notFound: "الصفحة غير موجودة.",
    serverError: "حدث خطأ غير متوقع. أعد المحاولة.",
  },

  metadata: {
    home: {
      title: "مستشفى نبض",
      description:
        "مستشفى نبض — رعاية صحية موثوقة ومواعيد تحجزها في دقائق مع نخبة من الأطباء.",
    },
    about: {
      title: "عن المستشفى",
      description: "نبذة عن مستشفى نبض وأقسامه وفريقه الطبي في الرياض.",
    },
    departments: {
      title: "الأقسام",
      description: "أقسام مستشفى نبض الطبية الستة وأطباء كل قسم.",
    },
    doctors: {
      title: "الأطباء",
      description: "تصفّح أطباء مستشفى نبض واحجز موعدك مع الطبيب المناسب.",
    },
    faq: {
      title: "الأسئلة الشائعة",
      description: "إجابات عن أكثر الأسئلة شيوعًا حول مواعيد وخدمات مستشفى نبض.",
    },
    contact: {
      title: "تواصل معنا",
      description: "معلومات التواصل مع مستشفى نبض ونموذج إرسال الاستفسارات.",
    },
    login: {
      title: "تسجيل الدخول",
      description: "سجّل الدخول إلى حسابك في مستشفى نبض لإدارة مواعيدك.",
    },
    register: {
      title: "إنشاء حساب",
      description: "أنشئ حسابًا في مستشفى نبض لحجز المواعيد ومتابعتها.",
    },
    adminLogin: {
      title: "دخول الإدارة",
      description: "بوابة دخول موظفي مستشفى نبض.",
    },
  },
} as const;

export type Content = typeof ar;

export default ar;
